### PR TITLE
Optimize Images

### PR DESCRIPTION
**Pull request by ConcaveTrillion**
- [Art] Optimize SVGs
- [Art] Optimize JPEGs

### CODE REVIEW

**Comment by ConcaveTrillion** [comment]
After doing the four men I found a lot of better ways to optimize images. This should significantly reduce the size of the single-page view as well as the ebook itself. Also, it fixes a lint issue where the SVG title doesn't match the alt text in the book ("an an") was fixed in text but not svg.

**Comment by acabal** [comment]
What exactly did you do here?

**Comment by ConcaveTrillion** [comment]
- For the SVGs: I ran all the SVG's through SVGOMG, and reduced precision on the digits in the paths by several orders of magnitude, without loss of image fidelity. The typical space savings was anywhere from 50% - 80%. I then verified all the SVG images still build to PNGs properly by running a build and extracting all the PNGs to ensure they were all OK.

- For JPEGs: reduced 'quality' level of JPEGs to '60%' in GIMP, without any noticable loss of image fidelity.

- EPUB should go from ~20MB to ~10MB.
- Advanced EPUB from ~18MB to ~5MB
- Single-Page recomposed book should go from ~20MB to ~10MB.

**Comment by acabal** [comment]
OK. Did you reduce the JPG quality starting from the JPGs in `./src/epub/images/`?  Because then they're double compressed. We must make sure to start from the images in `./images/` which are the uncompressed sources.

**Comment by ConcaveTrillion** [comment]
I had processed the originals via GIMP, doing color correction, levels adjustment, retouching of photographic artifacts due to age/imaging process, crop, etc. After that, I had exported them at the "100%" quality setting (sources were also jpegs), so no additional compression should have been applied at the time. 

If you'd rather, I can see if I still have the GIMP versions of the intermediate workflow, or, if you want, just take the commit with the SVGs alone.

**Comment by acabal** [comment]
JPGs is a lossy format by definition, and every time you save a JPG it becomes more degraded even if you specify no compression. That's why we keep the sources in `./images/`, so that if we need to go back and make changes we can start from the originals. If you're recompressing the JPGs, then you need to start from the sources in `./images/` and not the distributable JPGs in `./src/epub/images/`

**Comment by acabal** [comment]
Hi CT, if you don't have time to revisit the JPGs then we can merge in just the SVGs. Do you want to amend this commit to only change SVGs?

**Comment by ConcaveTrillion** [comment]
Sure. Sorry, I had a family emergency in May and haven't had much time to
work on this. I did start work on the JPGs, but I can amend for SVGs and
revisit the jpegs in the future.

**Comment by ConcaveTrillion** [comment]
Dropped the JPEG changes for now. Will revisit when I get a chance after I finish read of Cleopatra.

**Comment by acabal** [comment]
Excellent, thanks!

**Pull request merged**
